version: '3.8'

services:
  web:
    build: .
    ports:
      - "8701:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 